baseURL = '/writings/'
languageCode = 'en-us'
title = 'Tucker McLean - Writings'
theme = 'terminal'

[params]
  [params.logo]
    logoText = 'Tucker McLean - Writings'
  description = "Tucker McLean's writings and thoughts"
  author = "Tucker McLean"
  customCSS = ["css/custom.css"]
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true
  showLastUpdated = true

[build]
  writeStats = true

[permalinks]
  posts = '/posts/:slug/'

[server]
  [[server.headers]]
    for = '/**'
    [server.headers.values]
      X-Frame-Options = 'SAMEORIGIN'
      X-Content-Type-Options = 'nosniff'
      X-XSS-Protection = '1; mode=block'
