name: Deploy Frontend to S3

on:
  push:
    branches:
      - master  # Run this workflow on pushes to the main branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 1.5: Install Hugo
    - name: Install Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.115.4'
        extended: true

    # Step 2: Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Adjust the Node.js version as needed

    # Step 3: Install dependencies and build
    - name: Install Dependencies and Build
      run: |
        npm install
        npm run build  # Replace with your build script (e.g., "npm run build")

    # Step 3.5: List built files for debugging
    - name: List built files for debugging
      run: |
        find dist/writings

    # Step 4: Configure AWS credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Step 5: Deploy to S3
    - name: Deploy to S3
      run: |
        aws s3 sync ./dist s3://${{ secrets.S3_BUCKET_NAME }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
